tilezen/tileops

- batch-setup/make_meta_tiles.py
- batch-setup/make_rawr_tiles.py
- docker/meta-batch/config.yaml
- docker/rawr-batch/config.yaml
Ooops, looks like the source name here was wrong (still `whosonfirst.mapzen.com`), and was causing exceptions to be thrown.
Also, a couple of small improvements:
* Don't try to enqueue empty lists of tiles. Count the low and high lists separately.
* Print info about the time while waiting for jobs to finish.
> Fix WOF source name

- batch-setup/batch.py
- batch-setup/make_meta_tiles.py
- batch-setup/make_tiles.py
Connects to https://github.com/tilezen/tilequeue/pull/346
Enqueue jobs to check if the metatile exists before processing only on subsequent runs.
> Add check_metatile_exists option to batch enqueue

- batch-setup/make_tiles.py
Connects to https://github.com/tilezen/tilequeue/pull/347
This updates the batch enqueue config files to set the job-type appropriately.
> Set the batch enqueue job-type appropriately

- utils/count_jobs.py
- utils/list-batch-logs.py
- utils/meta-high-job-times.py
These are:
* `count_jobs.py` - Gives the true count of jobs in a Batch job queue by status, without the `1000+` that the Batch web console gives. Useful when the difference between 1,001 and 10,000 is meaningful.
* `list-batch-logs.py` - Lists the stacktraces found in the logs of all the Batch jobs completed in the past 24h. Can cut down the amount of time it takes to figure out why certain tiles are missing.
* `meta-high-job-times.py` - Lists the time taken by each high-zoom (i.e: RAWR-based) job in the past 24h. Can be useful for figuring out which jobs to focus optimisation efforts on.
> Add a few scripts that I've found useful.

- utils/cwtail.py
For some reason that I don't currently understand (#13), the logs from the TPS instance are being ingested with an event timestamp of the time that the process was started. This makes it _really_ hard to follow along the logs in the CloudWatch console. It's probably a bug, but while this instance was running, I found this script helpful to "follow along" the logs and check its status.
> Add utility to watch CW logs from TPS instance.

- docker/meta-batch/Dockerfile
- docker/meta-batch/config.yaml
- docker/meta-batch/requirements.txt
- docker/meta-low-zoom-batch/Dockerfile
- docker/meta-low-zoom-batch/config.yaml
- docker/meta-low-zoom-batch/requirements.txt
Add configuration to go along with https://github.com/tilezen/tilequeue/pull/350 - this switches the driver used in tileops from `mvt` to `coanacatl` (still writes MVT, just via [Wagyu](https://github.com/mapbox/wagyu) rather than [mapbox-vector-tile](https://github.com/tilezen/mapbox-vector-tile)). 
**Reminder: Do not merge until https://github.com/tilezen/coanacatl/pull/1 is merged and the `requirements.txt` Git branches can be reset back to `master` - or a release tag.**
> Update Docker images to install coanacatl.

- batch-setup/cron.py
- batch-setup/make_meta_tiles.py
- batch-setup/provision.sh
Looks like the default max zoom to check for missing tiles is 14, which means that it'll think that _all_ zoom 14 tiles are missing if the metatile size is larger than 4x4. Instead, the max zoom to check should be based on the metatile size, which has been added as an argument.
> Make metatile size and max zoom configurable.

- batch-setup/cron.py
- batch-setup/make_meta_tiles.py
- batch-setup/make_rawr_tiles.py
- batch-setup/provision.sh
- import/import.py
I made a bunch of silly bugs, including:
1. Adding the `-max-zoom` argument to _the wrong external command_.
2. Forgetting to check for other uses of `MissingTileFinder`, whose signature I'd changed so that it no longer worked from the other invocation site.
3. Checking whether a database snapshot existed _after_ a different check, where the other check was erroring out rather than skipping the import without error.
> Fix bugs in "skip import if DB snapshot exists"

- buildspec.yml
- utils/count_jobs.py
- utils/cwtail.py
The major change here is to allow specifying code versions in the Codebuild environment. This allows us to kick off one-off jobs from branched code, or to pin code versions for regular scheduled builds.
Also, there's a change which uses `t2.medium` instead of `t2.micro` for the TPS instance. I'd prefer to use the smaller instance, but it turns out that 1GiB of memory isn't enough to compile coanacatl. @iandees is there any way to precompile the extension in that package so it doesn't need to be compiled at install time? Quite apart from the extra RAM it needs, it takes quite a long time!
Also, a couple of unrelated (sorry) changes to utilities to allow more configurability in the job queue monitor and better event filtering in the log watcher.
> Allow specifying code versions in Codebuild environment

- batch-setup/cron.py
- batch-setup/provision.sh
- docker/meta-batch/requirements.txt
- docker/meta-low-zoom-batch/requirements.txt
To allow for a separate build re-using the databases and RAWR tiles, but making sure we're not mixing up with previous tiles in the meta tile bucket. Also bump coanacatl version to get Y coordinate flip fix.
> Configure meta date prefix separately

- batch-setup/batch.py
- batch-setup/cancel_all_jobs.py
- batch-setup/provision.sh
Left this out of a previous PR, but the `make_tiles.py` script needs to know the meta date prefix, if it's different from the regular date prefix, so that it can set up the job definition and permissions correctly.
Also, an unrelated change to call `cancel_job` on some types of jobs - apparently terminate only works on running (or starting) jobs, and will silently fail on jobs in other statuses. Refactored the cancel all jobs script to use the code already in `batch.py`.
> Add meta date prefix to call to make_tiles.py

- batch-setup/batch.py
- batch-setup/make_meta_tiles.py
- batch-setup/make_rawr_tiles.py
- docker/meta-batch/requirements.txt
- docker/meta-low-zoom-batch/requirements.txt
- utils/cwtail.py
Add better support for having a different date prefix on the meta bucket vs. all other buckets.
Also, make it easier to tail logs for different environments, not just the most recent.
Finally, bump `coanacatl` version to latest to pick up bug fix.
> Better support for different prefix on meta bucket

- batch-setup/batch.py
- batch-setup/cron.py
- batch-setup/ecr.py
- batch-setup/make_meta_tiles.py
- batch-setup/make_tiles.py
- batch-setup/provision.sh
- batch-setup/rds.py
- batch-setup/run_id.py
- batch-setup/teardown.py
- buildspec.yml
- import/database.py
- import/import.py
- import/osm2pgsql.py
- utils/cwtail.py
Previously, all runs had been identified by the planet date they're generated from. This leads to problems when we want to run two concurrent, different runs off the same planet. To make sure resources are unique to the run rather than the planet file, this PR changes to name resources using the run ID instead. The previous behaviour should be (almost) emulated by specifying the run ID as `YYMMDD`.
There are a few things, notably PostgreSQL database names, which used a `YYYY-MM-DD` format instead, and these will be incompatible. However, I think the gain is worth the hassle of having to manually go back and correct any of those which might still be running.
Possibly helps towards #16.
> Use run ID instead of date prefix for resource naming.

- Pipfile
- Pipfile.lock
- batch-setup/provision.sh
- import/requirements.txt
- utils/setup.sh
Add a script which does a lot of the work of setting up buckets, static assets and a Codebuild policy.
For some reason, I'm not getting CloudWatch logs out of this new setup - but otherwise it seems to be working fine.
> Add setup script

- import/database_looks_finished.sh
- utils/setup.sh
There were a couple of big problems which meant the environment hadn't been set up correctly, so I've tried to back-port these to the setup script.
1. On my desktop Linux system, Go binaries were dynamically linked to `libc`, which works great on my system. However, on an Alpine Linux container, which uses a different `libc` implementation, it failed to run. Fixed this by disabling CGO, which seems to be the default behaviour when cross-compiling on Mac OS.
2. Use the correct name for the missing tiles bucket :man_facepalming: 
3. Add an `ecsInstanceRole` role and instance profile which match what we default to in the scripts.
> Fix some issues with setup script

- docker/meta-batch/requirements.txt
- docker/meta-low-zoom-batch/requirements.txt
- docker/rawr-batch/requirements.txt
- import/requirements.txt
- utils/setup.sh
Fixes the security alert that Github pops up with on the repo! :lock:
> Update requests to 2.20.0 because CVE-2018-18074.

- batch-setup/batch.py
When we use environment overrides to pass environment variables to the Batch jobs, they're already stringified as JSON, so we don't need to do it again.
> Fix double-quoting bug for environment overrides

- import/import_planet.sh
Environment variables for the user do not get implicitly forwarded to the `sudo` environment. Although generally a good thing for security reasons, it is easy to forget about. In this case, the `DEBIAN_FRONTEND=noninteractive` environment variable was set for the user but not explicitly set in `sudo`, so `apt` was hanging waiting for console input that never arrived.
To fix, explicitly set `DEBIAN_FRONTEND` in all calls to `sudo apt ...` to avoid interactive fallback.
> Fix sudo environment for apt

- batch-setup/batch.py
Turns out, S3 tags are [pretty expensive](https://aws.amazon.com/s3/pricing/) - at current prices, putting two tags on each is equivalent to storing an extra 100kB. And most metatiles aren't even that big, as most are just water (about 4kB).
We had originally envisioned the tags as a neat way to tell which dataset a metatile was part of, which run rendered it, and as a quick way to delete them using S3 Bucket Lifecycle rules. For the former, it's already part of the URL, we can add comments to zipfiles as an alternative way of annotating the run ID, and [S3 Batch Operations](https://aws.amazon.com/about-aws/whats-new/2018/11/s3-batch-operations/) might be a more cost-effective way to delete large numbers of tiles.
This disables setting the tags by default, and can be overridden with …
> Don't set tags on S3 objects by default.

- batch-setup/make_meta_tiles.py
- batch-setup/tileset.py
When we're processing jobs in AWS Batch, there's always a "long tail" of jobs which take much longer than others to complete. This is partly because we group 64 items of work at zoom 10 together into one Batch job at zoom 7, and these aren't able to take advantage of any concurrency. The grouping at zoom 7 is useful to reduce overall job count and we don't want to get rid of it entirely. Instead, if we can detect these "big" jobs and submit only the "big" items of work as individual jobs, while still grouping the "small" items together, then we'll be better able to use the number of processors available to us.
This PR does that, by:
1. Finding the set of zoom 7 groups of RAWR tiles where the sum of the sizes of the RAWR tiles is large (the `--size-threshold` CLI argument, defaults to …
> Reduce high zoom "long tail" of jobs

- batch-setup/cron.py
[PR #47](https://github.com/tilezen/tileops/pull/47) added a feature to vary Batch job sizes according to the size of RAWR tiles, but missed the permission to read the RAWR tile S3 bucket, meaning all the requests failed.
> Allow TPS instance to read RAWR tiles.

- batch-setup/make_meta_tiles.py
Rendering high zoom tiles is done entirely from RAWR tiles, and the databases are not used at all. Due to their larger number and long tail of complex long-running jobs, this means we're keeping a lot of expensive databases running for no reason.
Splitting the low zoom (DB) from the high zoom (RAWR) potentially is less efficient, as the RAWR and DB jobs can't mix together and make full use of CPU and network resources. This loss of efficiency is probably several orders of magnitude less than leaving ten databases idle for a day or two!
This patch abstracts the rendering loop away from high and low zoom tiles, and inserts a command to shut down the databases between the two invocations.
Connects to #15.
> Shut down databases after low zoom rendering

- docker/meta-batch/requirements.txt
- docker/meta-low-zoom-batch/requirements.txt
- docker/rawr-batch/requirements.txt
- utils/setup.sh
Bump version of PyPROJ in `requirements.txt` files used in Docker and TPS provisioning script to v2.1.0, which provides the `Transformer` interface we'll be using in `tilequeue` if https://github.com/tilezen/tilequeue/pull/371 gets merged.
> Bump PyPROJ version to v2.1.0 for new Transformer interface.

- docker/meta-batch/config.yaml
- docker/rawr-batch/config.yaml
Update configuration files used in AWS Batch builds for RAWR tiles and high-zoom metatiles to use new source for osmdata land and water polygons.
Connects to tilezen/vector-datasource#1855.
> Update osmdata source, now hosted at osmdata.openstreetmap.de.

- README.md
- import/import.py
- import/import_planet.sh
- import/osm2pgsql.py
Adds a feature to specify a URL to download from instead of calculating the URL to the `osm-pds` bucket using the "planet date" value. Specifying the `--planet-url` option also makes MD5 checksumming optional. Add the `--planet-md5-url` argument to download and use that file to checksum the planet downloaded with `--planet-url`.
> Allow specifying a URL for planet instead of assuming the osm-pds S3

- import/osm.py
Rather than fixing the `HTMLParser` dependency, I switched to parsing the redirect URL for planet-latest.
> Remove HTMLParser dependency by parsing HTTP redirect on planet-latest

- batch-setup/batch.py
- docker/meta-batch/Dockerfile
* Added `/usr/bin/time` to the docker container and 
* wrap the meta-batch gen command in `time` so we can report some stats on each run
* I validated this formatting works using a modified job from the last global build.  Here's what it logs:
> Log resource stats for each run

- go/cmd/tz-missing-meta-tiles-write/missing-meta-tiles-write.go
This was being heavily throttled by s3, so much so that we were reporting tiles as missing because the searches for those got throttled too many times.  It actually appears to be as fast, possibly faster, with less goroutines due to the reduced thrashing.
> Reducing concurrency

- batch-setup/make_meta_tiles.py
- batch-setup/make_tiles.py
- multiply mem request by 1.5^retry_number for every batch job
- Verified in a python shell using the output of `tilequeue.Command#make_config_from_argparse`
> lowering memory requests, adding exponential mem increase on batch job retry

- Pipfile
- Pipfile.lock
- batch-setup/make_meta_tiles.py
- batch-setup/make_rawr_tiles.py
- batch-setup/provision.sh
- doc/batch/README.md
- doc/python_setup.md
- utils/constants.py
- utils/test_tiles.py
- utils/tiles.py
Add bounding box rebuild ability
After each global build, we might want to rebuild the area in a certain bounding box, so adding the ability to achieve that.
Triggered the build using a few bounding boxes and verified the tiles manually.
> add implementation of missing tiles generator

- batch-setup/batch_setup.py
We don't need the 8GB/cpu R5's for these builds.
> update instance type to standard m5.  4GB mem/cpu

- batch-setup/make_meta_tiles.py
- batch-setup/make_rawr_tiles.py
The tileops uses a few different names than that on tilequeue even though it calls the tilequeue for tile building; so rename some terminologies there to make them consistent.
The single source of the zoom values should all be from the config https://github.com/tilezen/tileops/blob/master/batch-setup/make_tiles.py#L163
This will make our V2 build easier too.
> Unify the zoom terminologies

- batch-setup/cron.py
- batch-setup/make_meta_tiles.py
- batch-setup/make_rawr_tiles.py
- utils/tiles.py
Add a verification step after the bounding box build step to verify all the s3 object (tiles) that should be updated are actually updated.
1. Add the meta tiles s3 bucket to the inline policy of the tileops so that the script has the permission to list and get meta tiles objects
2. Change the implementation of `generate_missing_tile_coords` to return generator instead of set of coordinates strings since it may be too large to fit into memory
2. Add the implementation of tiles generate and verification to a class S3TileVerififier and use it to do tiles s3 object updated time verification
> Add bbox build verification

- batch-setup/make_meta_tiles.py
there is a variable name bug introduced, fixing that.
> fix a bug of tileops coords

- batch-setup/make_meta_tiles.py
a bug was introduced for coords generation, so fixing that.
The correct version should match the left part of commit diff here.
https://github.com/tilezen/tileops/pull/90/commits/32fbe41a5cdeb18191a52cb5561e72626a5abf85
> fixbug of get_coord again

- docker/meta-batch/requirements.txt
- docker/meta-low-zoom-batch/requirements.txt
- docker/rawr-batch/requirements.txt
We updated this in vector-datasource, but neglected to in tileops.
> adding hanzidentifier to the batch job defs

- batch-setup/make_meta_tiles.py
- batch-setup/make_rawr_tiles.py
1. Add more timestamp to the logs of the tile build process
1. Remove a make_rawr_tiles tag from a log since that function is used in both rawr and meta tiles build
1. Add queue name to the log
> Add timestamp to more logs

- import/database.py
Bump the disk space given to the osm2pgsql instance from 1600GB to 2500GB, since we were running out of space.
I also switched from a m6g.4xl to a m6g.8xl to get [`12 Gbps` networking instead of `Up to 10Gbps`](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html).
> Increase the amount of disk space for the osm2pgsql RDS instance

- import/import.py
In some cases, we want the flow to stop before snapshot creation, so adding a flag for that.
> Add flag to skip snapshot creation and instance deletion

- batch-setup/cron.py
- batch-setup/provision.sh
Need a way from cron.py to skip everything post-import. 
@iandees need your eyeballs to vet my scriptfu.
@peitili I need your eyeballs to make sure I'm passing the --skip-snapshot flag the way you intended.
> Plumb flag to skip post-import steps

- batch-setup/cron.py
- batch-setup/provision.sh
- import/import.py
- import/osm2pgsql.py
We sometimes don't want the osm2pgsql runner to be terminated after import when want to do a DB modifications directly on that runner instance later, thus we add the flag for that.
The implementation mechanism is similar to `--skip-post-import-steps` flag
> Add flag to not terminate osm2pgsql runner

- import/import_planet.sh
- import/osm2pgsql.py
In order to use the newer, faster osm2pgsql, we either have to build locally or ugrade to new ubuntu.  The newer ubuntu does not ship with osm2pgsql so I have to install it, no need to check if it's already there.
> Upgrading to new, faster osm2pgsql

- import/import_planet.sh
The version of pip with this newer version of Ubuntu has some backwards compatibility issues.  Need to install an old one
> install new version of pip during import_planet
